apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    path: prometheus
    repoURL: https://github.com/imedomri/prometheus-helm.git
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: preus
  project: default